name: marketna_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  date_time_format: ^2.0.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_otp_text_field: ^1.1.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.4
  internet_connection_checker_plus: ^2.2.0
  json_annotation: ^4.8.1
  permission_handler: ^11.1.0
  rive: ^0.13.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/gif/
    - assets/bottomNavbar/
    - assets/audio/
    - assets/icons/
    - assets/images/
    - assets/riv/

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/font/ReadexPro-ExtraLight.ttf
          weight: 200
        - asset: assets/font/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/font/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/font/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/font/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/font/ReadexPro-Bold.ttf
          weight: 700
